
      ALL_SERVICES_DATABASE_HOST: edgex-redis
      ALL_SERVICES_MESSAGEBUS_HOST: edgex-redis
      ALL_SERVICES_REGISTRY_HOST: edgex-core-consul
      APP_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_SUPPORT-NOTIFICATIONS_HOST: edgex-support-notifications
      CONNECTION__EDGEX__REDISMSGBUS__PORT: "6379"
      CONNECTION__EDGEX__REDISMSGBUS__PROTOCOL: redis
      CONNECTION__EDGEX__REDISMSGBUS__SERVER: edgex-redis
      CONNECTION__EDGEX__REDISMSGBUS__TYPE: redis
      DATABASECONFIG_NAME: redis.conf
      DATABASECONFIG_PATH: /run/redis/conf
      DEVICE_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      EDGEX__DEFAULT__PORT: "6379"
      EDGEX__DEFAULT__PROTOCOL: redis
      EDGEX__DEFAULT__SERVER: edgex-redis
      EDGEX__DEFAULT__TOPIC: edgex/rules-events
      EDGEX__DEFAULT__TYPE: redis
      EDGEX_ADD_KNOWN_SECRETS: redisdb[app-rules-engine],redisdb[device-rest],message-bus[device-rest],redisdb[device-virtual],message-bus[device-virtual],redisdb[app-sample],message-bus[app-sample]
      EDGEX_ADD_PROXY_ROUTE: ""
      EDGEX_ADD_REGISTRY_ACL_ROLES: app-sample
      EDGEX_ADD_SECRETSTORE_TOKENS: app-sample
      EDGEX_GROUP: "2001"
      EDGEX_PROFILE: rules-engine
      EDGEX_PROFILE: sample
      EDGEX_SECURITY_SECRET_STORE: "true"
      EDGEX_USER: "2002"
      EXTERNALMQTT_URL: tcp://edgex-mqtt-broker:1883
      INTERVALACTIONS_SCRUBAGED_HOST: edgex-core-data
      INTERVALACTIONS_SCRUBPUSHED_HOST: edgex-core-data
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: "59720"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      ROUTES_CORE_COMMAND_HOST: edgex-core-command
      ROUTES_CORE_CONSUL_HOST: edgex-core-consul
      ROUTES_CORE_DATA_HOST: edgex-core-data
      ROUTES_CORE_METADATA_HOST: edgex-core-metadata
      ROUTES_DEVICE_VIRTUAL_HOST: device-virtual
      ROUTES_RULES_ENGINE_HOST: edgex-kuiper
      ROUTES_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      ROUTES_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      ROUTES_SYS_MGMT_AGENT_HOST: edgex-sys-mgmt-agent
      SECRETSTORE_HOST: edgex-vault
      SECUREMESSAGEBUS_TYPE: redis
      SERVICE_HOST: edgex-app-rules-engine
      SERVICE_HOST: edgex-app-sample
      SERVICE_HOST: edgex-core-command
      SERVICE_HOST: edgex-core-data
      SERVICE_HOST: edgex-core-metadata
      SERVICE_HOST: edgex-device-rest
      SERVICE_HOST: edgex-device-virtual
      SERVICE_HOST: edgex-proxy-auth
      SERVICE_HOST: edgex-support-notifications
      SERVICE_HOST: edgex-support-scheduler
      SERVICE_HOST: edgex-ui-go
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_ACL_BOOTSTRAPTOKENPATH: /tmp/edgex/secrets/consul-acl-token/bootstrap_token.json
      STAGEGATE_REGISTRY_ACL_MANAGEMENTTOKENPATH: /tmp/edgex/secrets/consul-acl-token/mgmt_token.json
      STAGEGATE_REGISTRY_ACL_SENTINELFILEPATH: /consul/config/consul_acl_done
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      VAULT_ADDR: http://edgex-vault:8200
      VAULT_CONFIG_DIR: /vault/config
      VAULT_UI: "true"