apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app-rules-engine
  name: app-rules-engine
spec:
  ports:
    - name: "59701"
      port: 59701
      targetPort: 59701
  selector:
    io.kompose.service: app-rules-engine
status:
  loadBalancer: {}
