apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-edgex-network: "true"
        io.kompose.service: consul
    spec:
      containers:
        - args:
            - agent
            - -ui
            - -bootstrap
            - -server
            - -client
            - 0.0.0.0
          command:
            - /edgex-init/consul_wait_install.sh
          env:
            - name: EDGEX_ADD_REGISTRY_ACL_ROLES
              value: app-sample
            - name: EDGEX_GROUP
              value: "2001"
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: EDGEX_USER
              value: "2002"
            - name: PROXY_SETUP_HOST
              value: edgex-security-proxy-setup
            - name: SECRETSTORE_HOST
              value: edgex-vault
            - name: STAGEGATE_BOOTSTRAPPER_HOST
              value: edgex-security-bootstrapper
            - name: STAGEGATE_BOOTSTRAPPER_STARTPORT
              value: "54321"
            - name: STAGEGATE_DATABASE_HOST
              value: edgex-redis
            - name: STAGEGATE_DATABASE_PORT
              value: "6379"
            - name: STAGEGATE_DATABASE_READYPORT
              value: "6379"
            - name: STAGEGATE_READY_TORUNPORT
              value: "54329"
            - name: STAGEGATE_REGISTRY_ACL_BOOTSTRAPTOKENPATH
              value: /tmp/edgex/secrets/consul-acl-token/bootstrap_token.json
            - name: STAGEGATE_REGISTRY_ACL_MANAGEMENTTOKENPATH
              value: /tmp/edgex/secrets/consul-acl-token/mgmt_token.json
            - name: STAGEGATE_REGISTRY_ACL_SENTINELFILEPATH
              value: /consul/config/consul_acl_done
            - name: STAGEGATE_REGISTRY_HOST
              value: edgex-core-consul
            - name: STAGEGATE_REGISTRY_PORT
              value: "8500"
            - name: STAGEGATE_REGISTRY_READYPORT
              value: "54324"
            - name: STAGEGATE_SECRETSTORESETUP_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT
              value: "54322"
            - name: STAGEGATE_WAITFOR_TIMEOUT
              value: 60s
          image: hashicorp/consul:1.15.2
          name: edgex-core-consul
          ports:
            - containerPort: 8500
              hostIP: 127.0.0.1
          resources: {}
          volumeMounts:
            - mountPath: /consul/config
              name: consul-config
            - mountPath: /consul/data
              name: consul-data
            - mountPath: /edgex-init
              name: edgex-init
              readOnly: true
            - mountPath: /tmp/edgex/secrets/consul-acl-token
              name: consul-acl-token
            - mountPath: /tmp/edgex/secrets/edgex-consul
              name: consul-claim4
              readOnly: true
      hostname: edgex-core-consul
      restartPolicy: Always
      volumes:
        - name: consul-config
          persistentVolumeClaim:
            claimName: consul-config
        - name: consul-data
          persistentVolumeClaim:
            claimName: consul-data
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
            readOnly: true
        - name: consul-acl-token
          persistentVolumeClaim:
            claimName: consul-acl-token
        - name: consul-claim4
          persistentVolumeClaim:
            claimName: consul-claim4
            readOnly: true
status: {}
