apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: core-metadata
  name: core-metadata
spec:
  ports:
    - name: "59881"
      port: 59881
      targetPort: 59881
  selector:
    io.kompose.service: core-metadata
status:
  loadBalancer: {}
