apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rules-engine
  name: rules-engine
spec:
  ports:
    - name: "59720"
      port: 59720
      targetPort: 59720
  selector:
    io.kompose.service: rules-engine
status:
  loadBalancer: {}
