apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: security-secretstore-setup
  name: security-secretstore-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: security-secretstore-setup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-edgex-network: "true"
        io.kompose.service: security-secretstore-setup
    spec:
      containers:
        - env:
            - name: EDGEX_ADD_KNOWN_SECRETS
              value: redisdb[app-rules-engine],redisdb[device-rest],message-bus[device-rest],redisdb[device-virtual],message-bus[device-virtual],redisdb[app-sample],message-bus[app-sample]
            - name: EDGEX_ADD_SECRETSTORE_TOKENS
              value: app-sample
            - name: EDGEX_GROUP
              value: "2001"
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: EDGEX_USER
              value: "2002"
            - name: PROXY_SETUP_HOST
              value: edgex-security-proxy-setup
            - name: SECRETSTORE_HOST
              value: edgex-vault
            - name: SECUREMESSAGEBUS_TYPE
              value: redis
            - name: STAGEGATE_BOOTSTRAPPER_HOST
              value: edgex-security-bootstrapper
            - name: STAGEGATE_BOOTSTRAPPER_STARTPORT
              value: "54321"
            - name: STAGEGATE_DATABASE_HOST
              value: edgex-redis
            - name: STAGEGATE_DATABASE_PORT
              value: "6379"
            - name: STAGEGATE_DATABASE_READYPORT
              value: "6379"
            - name: STAGEGATE_READY_TORUNPORT
              value: "54329"
            - name: STAGEGATE_REGISTRY_HOST
              value: edgex-core-consul
            - name: STAGEGATE_REGISTRY_PORT
              value: "8500"
            - name: STAGEGATE_REGISTRY_READYPORT
              value: "54324"
            - name: STAGEGATE_SECRETSTORESETUP_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT
              value: "54322"
            - name: STAGEGATE_WAITFOR_TIMEOUT
              value: 60s
          image: nexus3.edgexfoundry.org:10004/security-secretstore-setup-arm64:latest
          name: edgex-security-secretstore-setup
          resources: {}
          volumeMounts:
            - mountPath: /edgex-init
              name: edgex-init
              readOnly: true
            - mountPath: /tmp/edgex/secrets
              name: security-secretstore-setup-claim1
            - mountPath: /tmp/kuiper
              name: kuiper-sources
            - mountPath: /tmp/kuiper-connections
              name: kuiper-connections
            - mountPath: /vault/config
              name: vault-config
            - mountPath: /run
              name: security-secretstore-setup-tmpfs0
            - mountPath: /vault
              name: security-secretstore-setup-tmpfs1
      hostname: edgex-security-secretstore-setup
      restartPolicy: Always
      volumes:
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
            readOnly: true
        - name: security-secretstore-setup-claim1
          persistentVolumeClaim:
            claimName: security-secretstore-setup-claim1
        - name: kuiper-sources
          persistentVolumeClaim:
            claimName: kuiper-sources
        - name: kuiper-connections
          persistentVolumeClaim:
            claimName: kuiper-connections
        - name: vault-config
          persistentVolumeClaim:
            claimName: vault-config
        - emptyDir:
            medium: Memory
          name: security-secretstore-setup-tmpfs0
        - emptyDir:
            medium: Memory
          name: security-secretstore-setup-tmpfs1
status: {}
