apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: security-proxy-setup
  name: security-proxy-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: security-proxy-setup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-edgex-network: "true"
        io.kompose.service: security-proxy-setup
    spec:
      containers:
        - command:
            - /edgex-init/proxy_setup_wait_install.sh
          env:
            - name: EDGEX_ADD_PROXY_ROUTE
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: PROXY_SETUP_HOST
              value: edgex-security-proxy-setup
            - name: ROUTES_CORE_COMMAND_HOST
              value: edgex-core-command
            - name: ROUTES_CORE_CONSUL_HOST
              value: edgex-core-consul
            - name: ROUTES_CORE_DATA_HOST
              value: edgex-core-data
            - name: ROUTES_CORE_METADATA_HOST
              value: edgex-core-metadata
            - name: ROUTES_DEVICE_VIRTUAL_HOST
              value: device-virtual
            - name: ROUTES_RULES_ENGINE_HOST
              value: edgex-kuiper
            - name: ROUTES_SUPPORT_NOTIFICATIONS_HOST
              value: edgex-support-notifications
            - name: ROUTES_SUPPORT_SCHEDULER_HOST
              value: edgex-support-scheduler
            - name: ROUTES_SYS_MGMT_AGENT_HOST
              value: edgex-sys-mgmt-agent
            - name: SECRETSTORE_HOST
              value: edgex-vault
            - name: STAGEGATE_BOOTSTRAPPER_HOST
              value: edgex-security-bootstrapper
            - name: STAGEGATE_BOOTSTRAPPER_STARTPORT
              value: "54321"
            - name: STAGEGATE_DATABASE_HOST
              value: edgex-redis
            - name: STAGEGATE_DATABASE_PORT
              value: "6379"
            - name: STAGEGATE_DATABASE_READYPORT
              value: "6379"
            - name: STAGEGATE_READY_TORUNPORT
              value: "54329"
            - name: STAGEGATE_REGISTRY_HOST
              value: edgex-core-consul
            - name: STAGEGATE_REGISTRY_PORT
              value: "8500"
            - name: STAGEGATE_REGISTRY_READYPORT
              value: "54324"
            - name: STAGEGATE_SECRETSTORESETUP_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT
              value: "54322"
            - name: STAGEGATE_WAITFOR_TIMEOUT
              value: 60s
          image: nexus3.edgexfoundry.org:10004/security-proxy-setup-arm64:latest
          name: edgex-security-proxy-setup
          resources: {}
          volumeMounts:
            - mountPath: /edgex-init
              name: edgex-init
              readOnly: true
            - mountPath: /vault/config
              name: vault-config
            - mountPath: /etc/nginx/templates
              name: nginx-templates
            - mountPath: /etc/ssl/nginx
              name: nginx-tls
            - mountPath: /tmp/edgex/secrets/security-proxy-setup
              name: security-proxy-setup-claim4
              readOnly: true
            - mountPath: /tmp/edgex/secrets/consul-acl-token
              name: consul-acl-token
              readOnly: true
      hostname: edgex-security-proxy-setup
      restartPolicy: Always
      volumes:
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
            readOnly: true
        - name: vault-config
          persistentVolumeClaim:
            claimName: vault-config
        - name: nginx-templates
          persistentVolumeClaim:
            claimName: nginx-templates
        - name: nginx-tls
          persistentVolumeClaim:
            claimName: nginx-tls
        - name: security-proxy-setup-claim4
          persistentVolumeClaim:
            claimName: security-proxy-setup-claim4
            readOnly: true
        - name: consul-acl-token
          persistentVolumeClaim:
            claimName: consul-acl-token
            readOnly: true
status: {}
