apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: security-proxy-auth
  name: security-proxy-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: security-proxy-auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/edgex-edgex-network: "true"
        io.kompose.service: security-proxy-auth
    spec:
      containers:
        - args:
            - entrypoint.sh
            - /security-proxy-auth
            - -cp=consul.http://edgex-core-consul:8500
            - --registry
          command:
            - /bin/sh
            - /edgex-init/ready_to_run_wait_install.sh
          env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: PROXY_SETUP_HOST
              value: edgex-security-proxy-setup
            - name: SECRETSTORE_HOST
              value: edgex-vault
            - name: SERVICE_HOST
              value: edgex-proxy-auth
            - name: STAGEGATE_BOOTSTRAPPER_HOST
              value: edgex-security-bootstrapper
            - name: STAGEGATE_BOOTSTRAPPER_STARTPORT
              value: "54321"
            - name: STAGEGATE_DATABASE_HOST
              value: edgex-redis
            - name: STAGEGATE_DATABASE_PORT
              value: "6379"
            - name: STAGEGATE_DATABASE_READYPORT
              value: "6379"
            - name: STAGEGATE_READY_TORUNPORT
              value: "54329"
            - name: STAGEGATE_REGISTRY_HOST
              value: edgex-core-consul
            - name: STAGEGATE_REGISTRY_PORT
              value: "8500"
            - name: STAGEGATE_REGISTRY_READYPORT
              value: "54324"
            - name: STAGEGATE_SECRETSTORESETUP_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT
              value: "54322"
            - name: STAGEGATE_WAITFOR_TIMEOUT
              value: 60s
          image: nexus3.edgexfoundry.org:10004/security-proxy-auth-arm64:latest
          name: edgex-proxy-auth
          ports:
            - containerPort: 59842
              hostIP: 127.0.0.1
          resources: {}
          volumeMounts:
            - mountPath: /edgex-init
              name: edgex-init
              readOnly: true
            - mountPath: /tmp/edgex/secrets/security-proxy-auth
              name: security-proxy-auth-claim1
              readOnly: true
      hostname: edgex-proxy-auth
      restartPolicy: Always
      volumes:
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
            readOnly: true
        - name: security-proxy-auth-claim1
          persistentVolumeClaim:
            claimName: security-proxy-auth-claim1
            readOnly: true
status: {}
